version: "3.8"

services:
  # Define the Nginx service
  nginx:
    image: nginx:latest # Use the latest Nginx image
    ports:
      - "80:80" # Expose port 80 on the host to port 80 in the container
    volumes:
      - ./html:/usr/share/nginx/html # Mount a folder for static content
